# Generated by Django 6.0.2 on 2026-05-18 06:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profiles',
            index=models.Index(fields=['role', 'status'], name='profile_role_status_idx'),
        ),
        migrations.AddIndex(
            model_name='profiles',
            index=models.Index(fields=['status', '-created_at'], name='profile_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherregistrations',
            index=models.Index(fields=['status', '-created_at'], name='tr_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherregistrations',
            index=models.Index(fields=['reviewed_by', 'status'], name='tr_reviewer_status_idx'),
        ),
    ]
