# Generated by Django 6.0.2 on 2026-05-31 03:16

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_searchhistory'),
    ]

    operations = [
        TrigramExtension(),
    ]
