# Generated by Django 6.0.1 on 2026-05-17 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_assignments_exam_allow_custom_input_and_more'),
        ('submissions', '0002_feedbacktemplates_rubricscores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Chưa bắt đầu'), ('running', 'Đang làm'), ('submitted', 'Đã nộp'), ('auto_submitted', 'Tự động nộp'), ('expired', 'Hết giờ'), ('cancelled', 'Đã hủy')], default='not_started', max_length=24)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('current_language', models.TextField(blank=True, null=True)),
                ('latest_draft', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('extra_time_minutes', models.IntegerField(default=0)),
                ('violation_count', models.IntegerField(default=0)),
                ('run_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to='assignments.assignments')),
                ('final_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_sessions', to='submissions.submissions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam_sessions',
                'ordering': ('-created_at',),
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ExamEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='submissions.examsessions')),
            ],
            options={
                'db_table': 'exam_events',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['session', '-created_at'], name='exam_events_session_ff1059_idx'), models.Index(fields=['event_type', '-created_at'], name='exam_events_event_t_387217_idx')],
            },
        ),
    ]
