# Generated by Django 6.0.1 on 2026-05-17 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_assignments_asg_cls_pub_due_idx_and_more'),
        ('submissions', '0003_examsessions_examevents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='examsessions',
            index=models.Index(fields=['assignment', 'status'], name='exam_asg_status_idx'),
        ),
        migrations.AddIndex(
            model_name='examsessions',
            index=models.Index(fields=['student', 'status'], name='exam_st_status_idx'),
        ),
        migrations.AddIndex(
            model_name='submissions',
            index=models.Index(fields=['assignment', 'student', 'status', '-submitted_at'], name='sub_asg_st_status_at_idx'),
        ),
    ]
