# Generated by Django 6.0.2 on 2026-05-18 06:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_assignments_asg_cs_exam_pub_idx_and_more'),
        ('submissions', '0004_examsessions_exam_asg_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='examevents',
            index=models.Index(fields=['-created_at'], name='exam_event_created_idx'),
        ),
        migrations.AddIndex(
            model_name='examsessions',
            index=models.Index(fields=['status', '-updated_at'], name='exam_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='examsessions',
            index=models.Index(fields=['status', 'ends_at'], name='exam_status_ends_idx'),
        ),
        migrations.AddIndex(
            model_name='examsessions',
            index=models.Index(fields=['violation_count', '-updated_at'], name='exam_warn_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='submissions',
            index=models.Index(fields=['status', '-submitted_at'], name='sub_status_at_idx'),
        ),
        migrations.AddIndex(
            model_name='submissions',
            index=models.Index(fields=['language', 'status', '-submitted_at'], name='sub_lang_status_at_idx'),
        ),
        migrations.AddIndex(
            model_name='submissions',
            index=models.Index(fields=['student', 'status', '-submitted_at'], name='sub_student_status_at_idx'),
        ),
        migrations.AddIndex(
            model_name='submissions',
            index=models.Index(fields=['assignment', 'status', '-submitted_at'], name='sub_asg_status_at_idx'),
        ),
    ]
