# Generated by Django 6.0.1 on 2026-05-18 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0010_assignmentfilerequirements'),
        ('submissions', '0005_examevents_exam_event_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionFileFeedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('file_url', models.TextField()),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'submission_file_feedbacks',
            },
        ),
        migrations.CreateModel(
            name='SubmissionFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField()),
                ('file_url', models.TextField()),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('mime_type', models.TextField(blank=True, null=True)),
                ('extension', models.CharField(blank=True, max_length=16, null=True)),
                ('checksum', models.CharField(blank=True, max_length=128, null=True)),
                ('storage_provider', models.CharField(default='cloudinary', max_length=40)),
                ('scan_status', models.CharField(choices=[('pending', 'Chờ quét'), ('skipped', 'Bỏ qua'), ('clean', 'An toàn'), ('failed', 'Quét lỗi'), ('blocked', 'Bị chặn')], default='pending', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'submission_files',
            },
        ),
        migrations.AddField(
            model_name='submissions',
            name='submission_mode_snapshot',
            field=models.CharField(choices=[('code', 'Lập trình'), ('file', 'Nộp file'), ('quiz', 'Trắc nghiệm')], default='code', max_length=16),
        ),
        migrations.AddField(
            model_name='submissions',
            name='submission_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='code_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='submissions',
            name='language',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='submissions',
            index=models.Index(fields=['submission_mode_snapshot', 'status', '-submitted_at'], name='sub_mode_status_at_idx'),
        ),
        migrations.AddField(
            model_name='submissionfilefeedbacks',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_files', to='submissions.submissions'),
        ),
        migrations.AddField(
            model_name='submissionfilefeedbacks',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_feedback_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissionfiles',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='submissions.submissions'),
        ),
        migrations.AddField(
            model_name='submissionfiles',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_submission_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='submissionfilefeedbacks',
            index=models.Index(fields=['submission', '-uploaded_at'], name='subfb_submission_at_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionfilefeedbacks',
            index=models.Index(fields=['uploaded_by', '-uploaded_at'], name='subfb_uploader_at_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionfiles',
            index=models.Index(fields=['submission', 'uploaded_at'], name='subfile_submission_at_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionfiles',
            index=models.Index(fields=['checksum'], name='subfile_checksum_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionfiles',
            index=models.Index(fields=['scan_status', '-uploaded_at'], name='subfile_scan_at_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionfiles',
            index=models.Index(fields=['extension', '-uploaded_at'], name='subfile_ext_at_idx'),
        ),
    ]
