# Generated by Django 6.0.1 on 2026-05-18 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0007_quizattempts_quizanswers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeChangeLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_manual_score', models.FloatField(blank=True, null=True)),
                ('new_manual_score', models.FloatField(blank=True, null=True)),
                ('previous_total_score', models.FloatField(blank=True, null=True)),
                ('new_total_score', models.FloatField(blank=True, null=True)),
                ('previous_status', models.CharField(blank=True, max_length=40, null=True)),
                ('new_status', models.CharField(blank=True, max_length=40, null=True)),
                ('previous_comment', models.TextField(blank=True, null=True)),
                ('new_comment', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_change_logs', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_change_logs', to='submissions.submissions')),
            ],
            options={
                'db_table': 'grade_change_logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['submission', '-created_at'], name='gcl_submission_created_idx'), models.Index(fields=['changed_by', '-created_at'], name='gcl_user_created_idx'), models.Index(fields=['-created_at'], name='gcl_created_idx')],
            },
        ),
    ]
