# Generated by Django 6.0.1 on 2026-05-18 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0014_backfill_v2_modes'),
        ('submissions', '0009_backfill_submission_mode_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIScoringSuggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('file_submission', 'Bài nộp file'), ('quiz_short_text', 'Quiz tự luận ngắn'), ('manual_review', 'Chấm tay tổng hợp')], default='file_submission', max_length=32)),
                ('suggested_score', models.FloatField(blank=True, null=True)),
                ('max_score', models.FloatField(blank=True, null=True)),
                ('suggestion', models.TextField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('prompt_version', models.CharField(blank=True, max_length=64, null=True)),
                ('model_name', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('ready', 'Sẵn sàng'), ('accepted', 'Đã chấp nhận'), ('rejected', 'Đã từ chối'), ('superseded', 'Đã thay thế')], default='draft', max_length=24)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('input_snapshot', models.JSONField(blank=True, default=dict, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_scoring_suggestions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='quizanswers',
            name='ai_suggested_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizanswers',
            name='ai_suggestion_metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='quizanswers',
            name='ai_suggestion_status',
            field=models.CharField(choices=[('not_requested', 'Chưa yêu cầu'), ('pending', 'Chờ gợi ý'), ('ready', 'Có gợi ý'), ('reviewed', 'Đã xem'), ('ignored', 'Bỏ qua')], default='not_requested', max_length=24),
        ),
        migrations.AddField(
            model_name='submissionfiles',
            name='extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissionfiles',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissionfiles',
            name='extraction_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissionfiles',
            name='text_extraction_status',
            field=models.CharField(choices=[('not_requested', 'Chưa yêu cầu'), ('pending', 'Chờ trích xuất'), ('extracted', 'Đã trích xuất'), ('failed', 'Trích xuất lỗi'), ('unsupported', 'Chưa hỗ trợ')], default='not_requested', max_length=24),
        ),
        migrations.AddIndex(
            model_name='quizanswers',
            index=models.Index(fields=['ai_suggestion_status'], name='quiza_ans_ai_status_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionfiles',
            index=models.Index(fields=['text_extraction_status', '-uploaded_at'], name='subfile_text_at_idx'),
        ),
        migrations.AddField(
            model_name='aiscoringsuggestions',
            name='accepted_by_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_ai_scoring_suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aiscoringsuggestions',
            name='quiz_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggestions', to='submissions.quizanswers'),
        ),
        migrations.AddField(
            model_name='aiscoringsuggestions',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='submissions.submissions'),
        ),
        migrations.AddIndex(
            model_name='aiscoringsuggestions',
            index=models.Index(fields=['submission', 'status', '-created_at'], name='ai_sug_sub_status_idx'),
        ),
        migrations.AddIndex(
            model_name='aiscoringsuggestions',
            index=models.Index(fields=['target_type', 'status'], name='ai_sug_target_status_idx'),
        ),
        migrations.AddIndex(
            model_name='aiscoringsuggestions',
            index=models.Index(fields=['accepted_by_teacher', '-accepted_at'], name='ai_sug_accept_teacher_idx'),
        ),
    ]
