# Generated by Django 6.0.2 on 2026-05-18 06:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activitylogs',
            index=models.Index(fields=['-created_at'], name='alog_created_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylogs',
            index=models.Index(fields=['user', '-created_at'], name='alog_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylogs',
            index=models.Index(fields=['resource_type', 'resource_id'], name='alog_resource_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylogs',
            index=models.Index(fields=['ip_address'], name='alog_ip_idx'),
        ),
        migrations.AddIndex(
            model_name='programminglanguages',
            index=models.Index(fields=['is_active', 'name'], name='pl_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='programminglanguages',
            index=models.Index(fields=['file_extension'], name='pl_extension_idx'),
        ),
        migrations.AddIndex(
            model_name='sandboxconfigs',
            index=models.Index(fields=['is_active', 'language'], name='sb_active_language_idx'),
        ),
        migrations.AddIndex(
            model_name='servermetrics',
            index=models.Index(fields=['-recorded_at'], name='metrics_recorded_idx'),
        ),
        migrations.AddIndex(
            model_name='servermetrics',
            index=models.Index(fields=['cpu_usage'], name='metrics_cpu_idx'),
        ),
        migrations.AddIndex(
            model_name='servermetrics',
            index=models.Index(fields=['memory_usage'], name='metrics_memory_idx'),
        ),
        migrations.AddIndex(
            model_name='servermetrics',
            index=models.Index(fields=['queue_length'], name='metrics_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='systemsettings',
            index=models.Index(fields=['updated_by', '-updated_at'], name='setting_updater_at_idx'),
        ),
        migrations.AddIndex(
            model_name='systemsettings',
            index=models.Index(fields=['-updated_at'], name='setting_updated_idx'),
        ),
    ]
