# Generated by hand to normalize subjects into a shared catalog and classroom links.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forward_migrate_classroom_subjects(apps, schema_editor):
    Subjects = apps.get_model('classrooms', 'Subjects')
    ClassroomSubjects = apps.get_model('classrooms', 'ClassroomSubjects')

    for subject in Subjects.objects.exclude(classroom__isnull=True).iterator():
        ClassroomSubjects.objects.get_or_create(
            classroom_id=subject.classroom_id,
            subject_id=subject.id,
            defaults={
                'assigned_by_id': subject.created_by_id,
                'is_active': True,
            },
        )


def reverse_migrate_classroom_subjects(apps, schema_editor):
    ClassroomSubjects = apps.get_model('classrooms', 'ClassroomSubjects')
    Subjects = apps.get_model('classrooms', 'Subjects')

    for link in ClassroomSubjects.objects.select_related('classroom', 'subject').iterator():
        subject = Subjects.objects.filter(id=link.subject_id).first()
        if subject and getattr(subject, 'classroom_id', None) is None:
            subject.classroom_id = link.classroom_id
            subject.save(update_fields=['classroom'])


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_subjects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_subject_links', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_subject_links', to='classrooms.classrooms')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_links', to='classrooms.subjects')),
            ],
            options={
                'db_table': 'classroom_subjects',
                'ordering': ('classroom_id', 'subject_id'),
                'unique_together': {('classroom', 'subject')},
            },
        ),
        migrations.AlterField(
            model_name='subjects',
            name='code',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='subjects',
            unique_together=set(),
        ),
        migrations.RunPython(forward_migrate_classroom_subjects, reverse_migrate_classroom_subjects),
        migrations.RemoveField(
            model_name='subjects',
            name='classroom',
        ),
        migrations.AlterModelOptions(
            name='subjects',
            options={'ordering': ('status', 'code')},
        ),
    ]
