# Generated by Django 6.0.1 on 2026-05-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0005_classroom_approval_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjects',
            unique_together=set(),
        ),
    ]
