# Generated by Django 6.0.1 on 2026-05-17 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0006_alter_subjects_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='classroommembers',
            index=models.Index(fields=['classroom', 'status'], name='cm_classroom_status_idx'),
        ),
        migrations.AddIndex(
            model_name='classroommembers',
            index=models.Index(fields=['student', 'status'], name='cm_student_status_idx'),
        ),
    ]
