# Generated by Django 6.0.2 on 2026-05-18 06:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administation', '0002_activitylogs_alog_created_idx_and_more'),
        ('classrooms', '0007_classroommembers_cm_classroom_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='classrooms',
            index=models.Index(fields=['status', 'is_active', '-created_at'], name='cls_status_active_at_idx'),
        ),
        migrations.AddIndex(
            model_name='classrooms',
            index=models.Index(fields=['teacher', 'status'], name='cls_teacher_status_idx'),
        ),
        migrations.AddIndex(
            model_name='classrooms',
            index=models.Index(fields=['is_active', '-created_at'], name='cls_active_created_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomsubjects',
            index=models.Index(fields=['classroom', 'is_active'], name='cs_classroom_active_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomsubjects',
            index=models.Index(fields=['subject', 'is_active'], name='cs_subject_active_idx'),
        ),
        migrations.AddIndex(
            model_name='classroomsubjects',
            index=models.Index(fields=['semester', 'is_active'], name='cs_semester_active_idx'),
        ),
        migrations.AddIndex(
            model_name='subjects',
            index=models.Index(fields=['status', 'is_active', '-created_at'], name='subj_status_active_at_idx'),
        ),
        migrations.AddIndex(
            model_name='subjects',
            index=models.Index(fields=['created_by', 'status'], name='subj_creator_status_idx'),
        ),
        migrations.AddIndex(
            model_name='subjects',
            index=models.Index(fields=['is_active', '-created_at'], name='subj_active_created_idx'),
        ),
    ]
