# Generated by Django 6.0.2 on 2026-05-31 04:21

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0008_classrooms_cls_status_active_at_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrooms',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='classrooms.semesters'),
        ),
    ]
