# Generated by Django 6.0.2 on 2026-05-31 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0009_add_semester_to_classrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classrooms',
            name='semester',
        ),
        migrations.AddField(
            model_name='classrooms',
            name='school_year',
            field=models.CharField(blank=True, help_text='VD: 2025-2026', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='classrooms',
            name='semester_term',
            field=models.CharField(blank=True, help_text='VD: Học kỳ 1', max_length=32, null=True),
        ),
    ]
