# Generated by Django 6.0.2 on 2026-05-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0010_remove_classrooms_semester_classrooms_school_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroommembers',
            name='status',
            field=models.TextField(blank=True, default='pending', null=True),
        ),
    ]
