# Generated by Django 6.0.2 on 2026-07-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0011_alter_classroommembers_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrooms',
            name='password',
            field=models.CharField(blank=True, help_text='Mật khẩu bảo vệ tham gia lớp học (tùy chọn)', max_length=50, null=True),
        ),
    ]
