# Generated by Django 6.0.1 on 2026-05-17 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_rubrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlagiarismReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('threshold', models.FloatField(default=0.85)),
                ('language', models.CharField(blank=True, max_length=40, null=True)),
                ('result', models.JSONField(blank=True, default=list)),
                ('submissions_count', models.IntegerField(default=0)),
                ('pairs_count', models.IntegerField(default=0)),
                ('suspicious_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_reports', to='assignments.assignments')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plagiarism_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plagiarism_reports',
                'ordering': ('-created_at',),
            },
        ),
    ]
