# Generated by Django 6.0.1 on 2026-05-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_plagiarismreports'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='exam_allow_custom_input',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='exam_allow_sample_run',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='exam_grace_seconds',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='assignments',
            name='exam_max_run_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='exam_require_fullscreen',
            field=models.BooleanField(default=False),
        ),
    ]
