# Generated by Django 6.0.1 on 2026-05-17 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_assignments_exam_allow_custom_input_and_more'),
        ('classrooms', '0007_classroommembers_cm_classroom_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assignments',
            index=models.Index(fields=['classroom', 'is_published', 'due_date'], name='asg_cls_pub_due_idx'),
        ),
        migrations.AddIndex(
            model_name='assignments',
            index=models.Index(fields=['classroom_subject'], name='asg_cls_subject_idx'),
        ),
    ]
