# Generated by Django 6.0.2 on 2026-05-18 06:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_assignments_asg_cls_pub_due_idx_and_more'),
        ('classrooms', '0008_classrooms_cls_status_active_at_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assignments',
            index=models.Index(fields=['classroom_subject', 'is_exam', 'is_published'], name='asg_cs_exam_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='assignments',
            index=models.Index(fields=['classroom', 'is_exam', 'is_published'], name='asg_cls_exam_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='assignments',
            index=models.Index(fields=['created_by', 'is_published'], name='asg_creator_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='assignments',
            index=models.Index(fields=['is_exam', '-created_at'], name='asg_exam_created_idx'),
        ),
    ]
