# Generated by Django 6.0.1 on 2026-05-18 13:13

from django.db import migrations, models


def seed_v2_modes(apps, schema_editor):
    Assignments = apps.get_model('assignments', 'Assignments')
    Assignments.objects.filter(type='auto_grade').update(
        submission_mode='code',
        grading_mode='auto',
    )
    Assignments.objects.filter(type__in=['manual_grade', 'project']).update(
        submission_mode='code',
        grading_mode='manual',
    )


def reverse_seed_v2_modes(apps, schema_editor):
    # Fields are removed by the migration rollback, no data rewrite needed.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_assignments_asg_cs_exam_pub_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='grading_mode',
            field=models.CharField(choices=[('auto', 'Tự động'), ('manual', 'Thủ công'), ('mixed', 'Kết hợp')], default='auto', max_length=16),
        ),
        migrations.AddField(
            model_name='assignments',
            name='submission_mode',
            field=models.CharField(choices=[('code', 'Lập trình'), ('file', 'Nộp file'), ('quiz', 'Trắc nghiệm')], default='code', max_length=16),
        ),
        migrations.RunPython(seed_v2_modes, reverse_seed_v2_modes),
    ]
