# Generated by Django 6.0.1 on 2026-05-18 13:19

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_assignments_grading_mode_assignments_submission_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentFileRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_extensions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), blank=True, default=list, help_text='VD: .pdf, .docx, .zip, .py')),
                ('allowed_mime_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list)),
                ('max_file_size_mb', models.PositiveIntegerField(default=20)),
                ('max_files', models.PositiveIntegerField(default=1)),
                ('require_comment', models.BooleanField(default=False)),
                ('allow_resubmit', models.BooleanField(default=True)),
                ('require_all_files_before_submit', models.BooleanField(default=True)),
                ('scan_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_requirements', to='assignments.assignments')),
            ],
            options={
                'db_table': 'assignment_file_requirements',
            },
        ),
    ]
