# Generated by Django 6.0.1 on 2026-05-18 13:54

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0010_assignmentfilerequirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('single_choice', 'Một đáp án'), ('multiple_choice', 'Nhiều đáp án'), ('true_false', 'Đúng/Sai'), ('short_text', 'Trả lời ngắn')], default='single_choice', max_length=24)),
                ('points', models.FloatField(default=1)),
                ('order_index', models.IntegerField(default=0)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('media_url', models.TextField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, default=list)),
                ('difficulty', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='assignments.assignments')),
            ],
            options={
                'db_table': 'quiz_questions',
                'ordering': ('order_index', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuizChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('order_index', models.IntegerField(default=0)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assignments.quizquestions')),
            ],
            options={
                'db_table': 'quiz_choices',
                'ordering': ('order_index', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuizSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_order_mode', models.CharField(choices=[('fixed', 'Cố định'), ('random', 'Ngẫu nhiên')], default='fixed', max_length=16)),
                ('choice_order_mode', models.CharField(choices=[('fixed', 'Cố định'), ('random', 'Ngẫu nhiên')], default='fixed', max_length=16)),
                ('show_score_after_submit', models.BooleanField(default=True)),
                ('show_correct_answers', models.BooleanField(default=False)),
                ('show_explanation', models.BooleanField(default=False)),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('passing_score', models.FloatField(blank=True, null=True)),
                ('allow_review', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_settings', to='assignments.assignments')),
            ],
            options={
                'db_table': 'quiz_settings',
            },
        ),
        migrations.AddIndex(
            model_name='quizquestions',
            index=models.Index(fields=['assignment', 'is_active', 'order_index'], name='quizq_asg_active_order_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestions',
            index=models.Index(fields=['assignment', 'question_type'], name='quizq_asg_type_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestions',
            index=models.Index(fields=['difficulty'], name='quizq_difficulty_idx'),
        ),
        migrations.AddIndex(
            model_name='quizchoices',
            index=models.Index(fields=['question', 'order_index'], name='quizc_question_order_idx'),
        ),
        migrations.AddIndex(
            model_name='quizchoices',
            index=models.Index(fields=['question', 'is_correct'], name='quizc_question_correct_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsettings',
            index=models.Index(fields=['question_order_mode'], name='quizset_q_order_idx'),
        ),
        migrations.AddIndex(
            model_name='quizsettings',
            index=models.Index(fields=['choice_order_mode'], name='quizset_c_order_idx'),
        ),
    ]
