# Generated by Django 6.0.1 on 2026-05-18 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0011_quizquestions_quizchoices_quizsettings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestionImports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(blank=True, null=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('success_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('clear_existing', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_question_imports', to='assignments.assignments')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_question_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_question_imports',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['assignment', '-created_at'], name='quizimp_asg_created_idx'), models.Index(fields=['imported_by', '-created_at'], name='quizimp_user_created_idx')],
            },
        ),
    ]
