# Generated by Django 6.0.1 on 2026-05-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0012_quizquestionimports'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='grades_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='show_feedback_after_release',
            field=models.BooleanField(default=True),
        ),
    ]
