# Generated by Django 6.0.2 on 2026-05-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0014_backfill_v2_modes'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='starter_code',
            field=models.TextField(blank=True, help_text='Mã nguồn hiện sẵn trong IDE khi học sinh mới mở bài.', null=True),
        ),
    ]
