# Generated by Django 6.0.2 on 2026-05-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0015_add_starter_code_to_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='solution_code',
            field=models.TextField(blank=True, help_text='Mã nguồn mẫu của giáo viên dùng để kiểm tra testcase.', null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='solution_language',
            field=models.TextField(blank=True, help_text='Ngôn ngữ của mã nguồn mẫu.', null=True),
        ),
    ]
