# Generated by Django 6.0.2 on 2026-06-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0016_assignments_solution_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='score_aggregation_mode',
            field=models.CharField(choices=[('best', 'Lấy điểm cao nhất'), ('latest', 'Lấy điểm lần cuối'), ('average', 'Lấy điểm trung bình'), ('first', 'Lấy điểm lần đầu')], default='best', max_length=12),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='max_score',
            field=models.FloatField(default=100),
        ),
    ]
