# Generated by Django 6.0.2 on 2026-08-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0017_assignments_score_aggregation_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='solution_codes',
            field=models.JSONField(blank=True, default=dict, help_text='Mã mẫu cho từng ngôn ngữ (Multiple languages)', null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='starter_codes',
            field=models.JSONField(blank=True, default=dict, help_text='Mã khởi tạo cho từng ngôn ngữ (Multiple languages)', null=True),
        ),
    ]
