from django.urls import path
from . import views

app_name = 'submissions'

urlpatterns = [
    path('solve/<int:assignment_pk>/', views.solve_problem_view, name='solve'),
    path('file/<int:assignment_pk>/', views.file_submission_view, name='file_submission'),
    path('file/<int:assignment_pk>/draft/clear/', views.clear_file_draft_view, name='clear_file_draft'),
    path('exam/<int:assignment_pk>/', views.exam_lobby_view, name='exam_lobby'),
    path('exam/<int:assignment_pk>/start/', views.start_exam_view, name='start_exam'),
    path('exam/<int:assignment_pk>/ide/', views.exam_ide_view, name='exam_ide'),
    path('exam/<int:assignment_pk>/ping/', views.exam_ping_view, name='exam_ping'),
    path('exam/<int:assignment_pk>/event/', views.exam_event_view, name='exam_event'),
    path('exam/<int:assignment_pk>/monitor/', views.exam_monitor_view, name='exam_monitor'),
    path('exam/<int:assignment_pk>/monitor/json/', views.exam_monitor_json_view, name='exam_monitor_json'),
    path('exam/<int:assignment_pk>/monitor/export/', views.exam_monitor_export_view, name='exam_monitor_export'),
    path('exam-session/<int:session_pk>/extend/', views.extend_exam_session_view, name='extend_exam_session'),
    path('exam-session/<int:session_pk>/force-submit/', views.force_submit_exam_session_view, name='force_submit_exam_session'),
    path('save-draft/', views.save_draft_view, name='save_draft'),
    path('run-test/<int:assignment_pk>/', views.run_test_view, name='run_test'),
    path('submit/<int:assignment_pk>/', views.submit_code_view, name='submit'),
    path('submit-file/<int:assignment_pk>/', views.submit_file_view, name='submit_file'),
    path('quiz/<int:assignment_pk>/', views.quiz_lobby_view, name='quiz_lobby'),
    path('quiz/<int:assignment_pk>/start/', views.start_quiz_attempt_view, name='start_quiz'),
    path('quiz/attempt/<int:attempt_pk>/', views.take_quiz_attempt_view, name='quiz_take'),
    path('quiz/attempt/<int:attempt_pk>/autosave/', views.autosave_quiz_answer_view, name='quiz_autosave'),
    path('quiz/attempt/<int:attempt_pk>/submit/', views.submit_quiz_attempt_view, name='quiz_submit'),
    path('quiz/attempt/<int:attempt_pk>/result/', views.quiz_result_view, name='quiz_result'),
    path('files/<int:file_pk>/open/', views.open_submission_file_view, name='open_file'),
    path('feedback-files/<int:file_pk>/open/', views.open_feedback_file_view, name='open_feedback_file'),
    path('history/<int:assignment_pk>/', views.submission_history_view, name='history'),
    path('detail/<int:pk>/', views.submission_detail_view, name='detail'),
    path('teacher-list/<int:assignment_pk>/', views.submission_list_teacher_view, name='teacher_list'),
    path('teacher-list/<int:assignment_pk>/grades.csv', views.export_assignment_grades_csv_view, name='export_grades_csv'),
    path('teacher-list/<int:assignment_pk>/files.zip', views.download_submission_files_zip_view, name='download_files_zip'),
    path('grade/<int:pk>/', views.grade_submission_view, name='grade'),
    path('comment/<int:pk>/', views.add_code_comment_view, name='add_comment'),
    path('grade/<int:pk>/feedback-template/<int:template_pk>/delete/', views.delete_feedback_template_view, name='delete_feedback_template'),
    path('resolve-comment/<int:pk>/', views.resolve_comment_view, name='resolve_comment'),
]
